### ISSUE TITLE
make_response_from_array broken in 0.1.2

### ISSUE THREAD

**Issue by chrisdebug** [chfw/pyexcel-webio#6]
My flask_restful api is using make_response_from_array. The api response for 0.1.2 is always returning a null. I forced my api to use 0.1.1 and it's working again.

**Comment by chfw** [comment]
Hi, I think it failed due to this commit: https://github.com/pyexcel/pyexcel-webio/commit/3dbc88fbefe4168d6c6bec3f7490d10dd2f383d9. 

What you will need to do is to call init_webio(your_response_method).

And if you are using Flask-Excel, please stay with 0.1.1. I will release next version of it soon, which shall work seamlessly.

**Comment by chfw** [comment]
https://github.com/pyexcel/Flask-Excel/issues/23

please take flask-excel 0.0.7 and you need to call init_excel function, which is newly required.

**Comment by chrisdebug** [comment]
Ok. This worked fore me:

```
$ pip freeze
Flask-Excel==0.0.7
pyexcel==0.5.1.1
pyexcel-io==0.4.2
pyexcel-webio==0.1.2
```

and added this to my code:
```
import flask_excel as excel
...
excel.init_excel(app)
```

**Comment by chfw** [comment]
Thats great. Thanks for reporting.
